// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Alexandru Negoita

// Load .env so `DATABASE_URL` is available when the Prisma CLI runs migrations
// locally. `dotenv` is a dependency, so this import always resolves; the
// deploy-time config (.prisma-migrate/, generated by the build workflow) does
// not import it and relies on the caller exporting the variable instead.
import 'dotenv/config'

import { defineConfig } from 'prisma/config'

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
})
