// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Alexandru Negoita

export const ICON_CATEGORIES = ["love","photo","nature","animals","music","communication","places","food","time","arrows","actions","shopping"] as const
export type IconCategory = (typeof ICON_CATEGORIES)[number]

/** Search keywords (space separated, English plus a few Romanian) and the picker category. Picker-only: the viewer never loads this. */
export const LUCIDE_META: Record<string, { c: IconCategory; t: string }> = {
  'alarm-clock': { c: 'time', t: "morning alarm clock" },
  'aperture': { c: 'photo', t: "camera photo pictures shutter exposure aperture" },
  'apple': { c: 'food', t: "fruit food healthy snack nutrition fresh produce grocery organic harvest vitamin red green juicy sweet tart bite orchard plant core raw diet apple" },
  'arrow-down': { c: 'arrows', t: "backwards reverse direction south arrow down" },
  'arrow-left': { c: 'arrows', t: "previous back direction west <- arrow left săgeată stânga" },
  'arrow-right': { c: 'arrows', t: "forward next direction east -> arrow right săgeată dreapta" },
  'arrow-up': { c: 'arrows', t: "forward direction north arrow up" },
  'at-sign': { c: 'communication', t: "mention at email message @ sign arond" },
  'award': { c: 'love', t: "achievement badge rosette prize winner award" },
  'baby': { c: 'love', t: "child childproof children baby bebeluș" },
  'backpack': { c: 'places', t: "bag hiking travel camping school childhood backpack" },
  'badge-check': { c: 'actions', t: "verified check badge" },
  'banknote': { c: 'shopping', t: "currency money payment banknote" },
  'bath': { c: 'places', t: "amenities services bathroom shower bath" },
  'bed-double': { c: 'places', t: "sleep hotel furniture bed double" },
  'beer': { c: 'food', t: "alcohol bar beverage brewery drink beer" },
  'bell': { c: 'communication', t: "alarm notification sound reminder bell notificare" },
  'bell-ring': { c: 'communication', t: "alarm notification sound reminder bell ring" },
  'bike': { c: 'places', t: "bicycle transport trip bike" },
  'bird': { c: 'animals', t: "peace freedom wing avian tweet bird" },
  'bookmark': { c: 'actions', t: "save favorite mark label attachment file stick pin read clip marker tag bookmark semn de carte" },
  'box': { c: 'shopping', t: "cube package container storage geometry 3d isometric box" },
  'brush': { c: 'photo', t: "clean sweep refactor remove draw paint color artist brush" },
  'building': { c: 'places', t: "organisation organization building" },
  'bus': { c: 'places', t: "bus vehicle transport trip" },
  'cake': { c: 'love', t: "birthday birthdate celebration party surprise gateaux dessert fondant icing sugar sweet baking cake tort" },
  'calendar': { c: 'time', t: "date month year event birthday birthdate calendar dată" },
  'calendar-check': { c: 'time', t: "date day month year event confirm subscribe schedule done todo tick complete task calendar check" },
  'calendar-days': { c: 'time', t: "date month year event calendar days" },
  'calendar-heart': { c: 'love', t: "date month year event heart favourite subscribe valentines day calendar" },
  'camera': { c: 'photo', t: "photography lens focus capture shot visual image device equipment photo webcam video camera cameră aparat foto" },
  'camera-off': { c: 'photo', t: "photo webcam video camera off" },
  'candy': { c: 'love', t: "sugar food sweet candy" },
  'car': { c: 'places', t: "vehicle drive trip journey car mașină" },
  'cat': { c: 'animals', t: "animal pet kitten feline cat" },
  'check': { c: 'actions', t: "done todo tick complete task check bifă" },
  'chef-hat': { c: 'food', t: "cooking food kitchen restaurant chef hat" },
  'cherry': { c: 'food', t: "fruit food cherry" },
  'chevron-down': { c: 'arrows', t: "backwards reverse slow dropdown chevron down" },
  'chevron-left': { c: 'arrows', t: "back previous less than fewer menu < chevron left" },
  'chevron-right': { c: 'arrows', t: "forward next more than greater menu code coding command line terminal prompt shell > chevron right" },
  'chevron-up': { c: 'arrows', t: "caret keyboard mac control ctrl superscript exponential power ahead fast ^ dropdown chevron up" },
  'chevrons-right': { c: 'arrows', t: "turn corner chevrons right" },
  'church': { c: 'places', t: "temple building church biserică" },
  'circle-alert': { c: 'actions', t: "warning alert danger exclamation mark circle" },
  'circle-check': { c: 'actions', t: "done todo tick complete task circle check" },
  'circle-pause': { c: 'music', t: "music audio stop circle pause" },
  'circle-play': { c: 'music', t: "music start run circle play" },
  'circle-plus': { c: 'actions', t: "add new increase increment positive calculate crosshair aim target scope sight reticule maximum upgrade extra operator join concatenate code coding + circle plus" },
  'circle-question-mark': { c: 'actions', t: "question mark circle question mark ajutor întrebare" },
  'circle-user': { c: 'communication', t: "person account contact circle user" },
  'circle-x': { c: 'actions', t: "cancel close delete remove times clear error incorrect wrong mistake failure linter multiply multiplication circle x" },
  'clapperboard': { c: 'photo', t: "movie film video camera cinema cut action television tv show entertainment clapperboard" },
  'clipboard': { c: 'actions', t: "copy paste clipboard" },
  'clock': { c: 'time', t: "time watch alarm clock ceas oră" },
  'cloud': { c: 'nature', t: "weather cloud nor" },
  'clover': { c: 'nature', t: "leaf luck plant clover" },
  'coffee': { c: 'food', t: "drink cup mug tea cafe hot beverage coffee cafea" },
  'compass': { c: 'places', t: "direction north east south west browser compass" },
  'contact': { c: 'communication', t: "user person family friend acquaintance listing networking contact" },
  'cookie': { c: 'love', t: "biscuit snack dessert food sweet bakery consent privacy legal tracking browser website cookie" },
  'copy': { c: 'actions', t: "clone duplicate multiple copy" },
  'credit-card': { c: 'shopping', t: "bank purchase payment cc credit card" },
  'croissant': { c: 'food', t: "bakery cooking food pastry croissant" },
  'crop': { c: 'photo', t: "photo image crop" },
  'crown': { c: 'love', t: "diadem tiara circlet corona king ruler winner favourite crown coroană" },
  'cup-soda': { c: 'food', t: "beverage cup drink soda straw water" },
  'disc-3': { c: 'music', t: "album music vinyl record cd dvd format dj spin rotate rpm disc 3" },
  'dog': { c: 'animals', t: "animal pet puppy hound canine dog" },
  'download': { c: 'actions', t: "import export save download descărcare" },
  'droplet': { c: 'nature', t: "water weather liquid fluid wet moisture damp bead globule droplet" },
  'drum': { c: 'music', t: "drummer kit sticks instrument beat bang bass backing track band play performance concert march music audio sound noise loud drum" },
  'ellipsis': { c: 'actions', t: "et cetera etc loader loading progress pending throbber menu options operator code coding spread rest more further extra overflow dots … ... ellipsis" },
  'expand': { c: 'arrows', t: "scale fullscreen maximize minimize contract expand" },
  'external-link': { c: 'communication', t: "outbound open share external link extern" },
  'eye': { c: 'photo', t: "view watch see show expose reveal display visible visibility vision preview read eye" },
  'eye-off': { c: 'photo', t: "view watch see hide conceal mask hidden visibility vision eye off" },
  'fast-forward': { c: 'music', t: "music fast forward" },
  'feather': { c: 'nature', t: "quill plume writing author literature poetry manuscript bird plumage lightweight soft feather" },
  'film': { c: 'photo', t: "movie video reel camera cinema entertainment film" },
  'fish': { c: 'animals', t: "dish restaurant course meal seafood pet sea marine fish" },
  'flag': { c: 'actions', t: "report marker notification warning milestone goal notice signal attention banner flag" },
  'flame': { c: 'nature', t: "heat burn light glow ignite passion ember fire lit burning spark embers smoke firefighter fireman department brigade station emergency flame" },
  'flower': { c: 'nature', t: "sustainability nature plant spring flower floare" },
  'flower-2': { c: 'nature', t: "sustainability nature plant flower 2" },
  'focus': { c: 'photo', t: "camera lens photo dashed focus" },
  'frame': { c: 'photo', t: "logo design tool frame" },
  'gem': { c: 'love', t: "diamond crystal ruby jewellery price special present gift ring wedding proposal marriage rubygems gem diamant bijuterie verighetă" },
  'gift': { c: 'love', t: "present box birthday party gift cadou" },
  'glasses': { c: 'love', t: "glasses spectacles ochelari" },
  'globe': { c: 'communication', t: "world browser language translate globe glob web" },
  'grid-3x3': { c: 'actions', t: "table rows columns grid 3x3" },
  'guitar': { c: 'music', t: "acoustic instrument strings riff rock band country concert performance play lead loud music audio sound noise guitar" },
  'hand-heart': { c: 'love', t: "love like emotion hand heart" },
  'handshake': { c: 'communication', t: "agreement partnership deal business assistance cooperation friendship union terms handshake" },
  'headphones': { c: 'music', t: "music audio sound headphones" },
  'heart': { c: 'love', t: "like love emotion suit playing cards heart inimă dragoste" },
  'heart-handshake': { c: 'love', t: "agreement charity help deal terms emotion together handshake heart parteneriat nuntă" },
  'hourglass': { c: 'time', t: "timer time sandglass hourglass" },
  'house': { c: 'places', t: "home living building residence architecture house casă" },
  'ice-cream-cone': { c: 'love', t: "gelato food ice cream cone" },
  'image': { c: 'photo', t: "picture photo image imagine poză" },
  'images': { c: 'photo', t: "picture photo multiple copy gallery album collection slideshow showcase images imagini poze galerie" },
  'inbox': { c: 'communication', t: "email inbox" },
  'info': { c: 'actions', t: "about advice clue details help hint indicator information knowledge notice status support tooltip info informații" },
  'key': { c: 'actions', t: "password login authentication secure unlock keychain key ring fob key" },
  'lamp': { c: 'places', t: "lighting household home furniture lamp" },
  'landmark': { c: 'places', t: "bank building capitol finance money museum art gallery hall institute pediment portico doric columns pillars classical architecture government institution monument site history historic library temple ancient structure landmark biserică clădire" },
  'laptop': { c: 'communication', t: "computer screen remote laptop" },
  'layout-grid': { c: 'actions', t: "app home start layout grid" },
  'leaf': { c: 'nature', t: "sustainability nature energy plant autumn leaf frunză" },
  'lightbulb': { c: 'shopping', t: "idea bright lights lightbulb" },
  'link': { c: 'communication', t: "chain url link legătură" },
  'list': { c: 'actions', t: "options list" },
  'locate': { c: 'places', t: "map gps location cross locate" },
  'lock': { c: 'actions', t: "security password secure admin lock lacăt" },
  'luggage': { c: 'places', t: "baggage luggage travel suitcase" },
  'mail': { c: 'communication', t: "email message letter unread mail scrisoare" },
  'map': { c: 'places', t: "location navigation travel map hartă" },
  'map-pin': { c: 'places', t: "location waypoint marker drop map pin locație" },
  'map-pinned': { c: 'places', t: "location waypoint marker drop map pinned" },
  'martini': { c: 'love', t: "cocktail alcohol beverage bar drink glass spirit party celebration mixer martini" },
  'maximize': { c: 'arrows', t: "fullscreen expand dashed maximize" },
  'medal': { c: 'love', t: "prize sports winner trophy award achievement medal" },
  'menu': { c: 'actions', t: "bars navigation hamburger options menu" },
  'message-circle': { c: 'communication', t: "comment chat conversation dialog feedback speech bubble message circle mesaj" },
  'message-square': { c: 'communication', t: "comment chat conversation dialog feedback speech bubble message square" },
  'messages-square': { c: 'communication', t: "comment chat conversation dialog feedback speech bubbles copy multiple discussion interview debate messages square" },
  'mic': { c: 'music', t: "record sound listen radio podcast microphone mic microfon" },
  'mic-vocal': { c: 'music', t: "lyrics voice listen sound music radio podcast karaoke singing microphone mic vocal" },
  'minimize': { c: 'arrows', t: "exit fullscreen close shrink minimize" },
  'minus': { c: 'actions', t: "subtract remove decrease decrement reduce negative calculate line divider separator horizontal rule hr html markup markdown --- toolbar operator code coding minimum downgrade minus scade" },
  'monitor': { c: 'communication', t: "tv computer desktop screen display external display screen sharing virtual machine vm monitor" },
  'moon': { c: 'nature', t: "dark night moon lună" },
  'mountain': { c: 'nature', t: "climb hike rock mountain" },
  'music': { c: 'music', t: "note quaver eighth note music muzică" },
  'music-2': { c: 'music', t: "quaver eighth note note music 2" },
  'navigation': { c: 'places', t: "location travel navigation" },
  'package': { c: 'shopping', t: "box container storage sealed delivery undelivered unopened packed archive zip module package" },
  'palette': { c: 'photo', t: "colors colours theme scheme paint watercolor watercolour artist palette" },
  'party-popper': { c: 'love', t: "emoji congratulations celebration party tada 🎉 🎊 excitement exciting excites confetti popper petrecere" },
  'pause': { c: 'music', t: "music stop pause pauză" },
  'paw-print': { c: 'animals', t: "pets vets veterinarian domesticated cat dog bear paw print" },
  'pen': { c: 'photo', t: "pencil change create draw writer writing biro ink marker felt tip stationery artist pen" },
  'pencil': { c: 'photo', t: "rubber edit create draw sketch draft writer writing stationery artist pencil" },
  'percent': { c: 'shopping', t: "percentage modulo modulus remainder % sale discount offer marketing percent" },
  'phone': { c: 'communication', t: "call phone telefon" },
  'piano': { c: 'music', t: "music audio sound noise notes chord keys octave acoustic instrument play pianist performance concert piano" },
  'pizza': { c: 'food', t: "pie quiche food pizza" },
  'plane': { c: 'places', t: "plane trip airplane avion" },
  'play': { c: 'music', t: "music audio video start run play redare" },
  'plus': { c: 'actions', t: "add new increase increment positive calculate toolbar crosshair aim target scope sight reticule maximum upgrade extra + plus adaugă" },
  'printer': { c: 'actions', t: "fax office device printer" },
  'puzzle': { c: 'shopping', t: "component module part piece puzzle" },
  'qr-code': { c: 'actions', t: "barcode scan link url information digital qr code" },
  'quote': { c: 'actions', t: "quotation quote citat" },
  'rabbit': { c: 'animals', t: "animal rodent pet pest bunny hare fast speed hop rabbit" },
  'radio': { c: 'music', t: "signal broadcast connectivity live frequency radio" },
  'rainbow': { c: 'nature', t: "colors colours spectrum light prism arc clear sunshine rainbow" },
  'refresh-cw': { c: 'arrows', t: "rotate reload rerun synchronise synchronize arrows circular cycle refresh cw" },
  'repeat': { c: 'arrows', t: "loop arrows repeat" },
  'rewind': { c: 'music', t: "music rewind" },
  'rocket': { c: 'shopping', t: "release boost launch space version rocket" },
  'rotate-cw': { c: 'arrows', t: "arrow right clockwise refresh reload rerun redo rotate cw" },
  'route': { c: 'places', t: "path journey planner points stops stations route" },
  'ruler': { c: 'actions', t: "measurements centimeters cm millimeters mm metre foot feet inches units size length width height dimensions depth breadth extent stationery ruler" },
  'sailboat': { c: 'places', t: "ship boat harbor harbour dock sailboat" },
  'salad': { c: 'food', t: "food vegetarian dish restaurant course meal side vegetables health salad" },
  'save': { c: 'actions', t: "floppy disk save" },
  'scan': { c: 'photo', t: "qr-code barcode checkout augmented reality ar target surveillance camera lens focus frame select box boundary bounds area square dashed scan" },
  'scissors': { c: 'actions', t: "cut snip chop stationery crafts scissors" },
  'search': { c: 'actions', t: "find scan magnifier magnifying glass lens locate explore discover enlarge zoom search caută" },
  'send': { c: 'communication', t: "email message mail paper airplane paper aeroplane submit send" },
  'settings': { c: 'actions', t: "cog edit gear preferences settings setări" },
  'share': { c: 'communication', t: "network connections share distribuie" },
  'share-2': { c: 'communication', t: "network connections share 2" },
  'shell': { c: 'nature', t: "beach sand holiday sealife fossil ammonite biology ocean terminal command line session bash zsh roll wrap chewing gum bubble gum sweet sugar hosepipe carpet string spiral spinner hypnotise hypnosis shell" },
  'shield-check': { c: 'actions', t: "cybersecurity secured safety protection protected guardian guarded armored armoured defense defence defended blocked threat prevention prevented antivirus vigilance vigilant active activated enabled detection scanned found strength strong tough invincible invincibility invulnerable undamaged audited admin verification verified certification certified tested passed qualified cleared cleaned disinfected uninfected task completed todo done ticked checked crest bravery shield check" },
  'ship': { c: 'places', t: "boat knots nautical mile maritime sailing yacht cruise ocean liner tanker vessel navy trip releases ship" },
  'shopping-bag': { c: 'shopping', t: "ecommerce cart purchase store shopping bag" },
  'shopping-cart': { c: 'shopping', t: "trolley cart basket e-commerce store purchase products items ingredients shopping" },
  'shuffle': { c: 'arrows', t: "music random reorder shuffle" },
  'signpost': { c: 'places', t: "navigation direction arrow wayfinding guide location pointer route indicator marker bidirectional left right east west signpost" },
  'skip-back': { c: 'music', t: "arrow previous music skip back" },
  'skip-forward': { c: 'music', t: "arrow skip next music forward" },
  'sliders-horizontal': { c: 'actions', t: "settings filters controls sliders horizontal" },
  'smartphone': { c: 'communication', t: "phone cellphone device mobile screen display touchscreen portable responsive smartphone" },
  'snowflake': { c: 'nature', t: "cold weather freeze snow winter snowflake" },
  'sofa': { c: 'places', t: "armchair furniture leisure lounge loveseat couch sofa" },
  'sparkle': { c: 'love', t: "star effect filter night magic shiny glitter twinkle celebration sparkle" },
  'sparkles': { c: 'love', t: "stars effect filter night magic sparkles scântei" },
  'sprout': { c: 'nature', t: "eco green growth leaf nature plant seed spring sustainability sprout" },
  'squirrel': { c: 'animals', t: "animal rodent pet pest nuts retrieve updates storage stash squirrel" },
  'star': { c: 'love', t: "bookmark favorite like review rating star stea" },
  'star-half': { c: 'love', t: "bookmark favorite like review rating star half" },
  'sticker': { c: 'photo', t: "reaction emotion smile happy feedback sticker" },
  'sun': { c: 'nature', t: "brightness weather light summer sun soare" },
  'sunrise': { c: 'nature', t: "weather time morning day sunrise" },
  'sunset': { c: 'nature', t: "weather time evening night sunset" },
  'tag': { c: 'shopping', t: "label badge ticket mark tag" },
  'tent': { c: 'nature', t: "tipi teepee wigwam lodge camping campsite holiday retreat nomadic native american indian wilderness outdoors tent" },
  'thermometer': { c: 'nature', t: "temperature celsius fahrenheit weather thermometer" },
  'thumbs-down': { c: 'actions', t: "dislike bad emotion thumbs down" },
  'thumbs-up': { c: 'actions', t: "like good emotion thumbs up apreciere" },
  'ticket': { c: 'time', t: "entry pass voucher event concert show perforated dashed ticket bilet" },
  'timer': { c: 'time', t: "time timer stopwatch" },
  'trash': { c: 'actions', t: "empty deletion cleanup junk clear garbage delete remove bin waste recycle discard binoculars rubbish trash șterge coș" },
  'tree-deciduous': { c: 'nature', t: "tree forest park nature deciduous" },
  'tree-pine': { c: 'nature', t: "tree pine forest park nature copac brad" },
  'trees': { c: 'nature', t: "tree forest park nature trees" },
  'triangle-alert': { c: 'actions', t: "warning alert danger exclamation mark linter triangle atenție avertisment" },
  'trophy': { c: 'love', t: "prize sports winner achievement award champion celebration victory competition tournament leaderboard ranking success reward cup first gold trophy" },
  'turtle': { c: 'animals', t: "animal pet tortoise slow speed turtle" },
  'tv': { c: 'communication', t: "television stream display widescreen high-definition hd 1080p 4k 8k smart digital video entertainment showtime channels terrestrial satellite cable broadcast live frequency tune scan aerial receiver transmission signal connection connectivity tv" },
  'umbrella': { c: 'nature', t: "rain weather umbrella" },
  'upload': { c: 'actions', t: "file upload încărcare" },
  'user': { c: 'communication', t: "person account contact user persoană" },
  'user-round': { c: 'communication', t: "person account contact user round" },
  'users': { c: 'communication', t: "group people users oameni invitați" },
  'users-round': { c: 'communication', t: "group people users round" },
  'utensils': { c: 'food', t: "fork knife cutlery flatware tableware silverware food restaurant meal breakfast dinner supper utensils mâncare" },
  'video': { c: 'photo', t: "camera movie film recording motion picture camcorder reel video" },
  'volume-2': { c: 'music', t: "music sound speaker volume 2" },
  'volume-x': { c: 'music', t: "music sound mute speaker volume x" },
  'wallet': { c: 'shopping', t: "money finance pocket wallet" },
  'wand-sparkles': { c: 'love', t: "magic wizard magician wand sparkles" },
  'watch': { c: 'time', t: "clock time watch" },
  'wheat': { c: 'food', t: "corn cereal grain gluten wheat" },
  'wind': { c: 'nature', t: "weather air blow wind" },
  'wine': { c: 'love', t: "alcohol beverage bar drink glass sommelier vineyard winery wine vin pahar" },
  'x': { c: 'actions', t: "cancel close cross delete ex remove times clear math multiply multiplication x închide" },
  'zap': { c: 'nature', t: "flash camera lightning electricity energy power quick zap" },
  'zoom-in': { c: 'arrows', t: "magnifying glass plus zoom in" },
  'zoom-out': { c: 'arrows', t: "magnifying glass plus zoom out" },
}
